var N = null;var sourcesIndex = {};
sourcesIndex["wayland_backend"] = {"name":"","dirs":[{"name":"rs","dirs":[{"name":"client","files":["mod.rs"]},{"name":"server","files":["client.rs","common_poll.rs","handle.rs","mod.rs","registry.rs"]}],"files":["debug.rs","map.rs","mod.rs","socket.rs","wire.rs"]},{"name":"sys","dirs":[{"name":"client","files":["mod.rs"]},{"name":"server","files":["mod.rs"]}],"files":["mod.rs"]},{"name":"types","files":["client.rs","mod.rs","server.rs"]}],"files":["core_interfaces.rs","lib.rs","protocol.rs"]};
sourcesIndex["wayland_client"] = {"name":"","files":["conn.rs","event_queue.rs","globals.rs","lib.rs"]};
sourcesIndex["wayland_cursor"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_egl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_protocols"] = {"name":"","files":["lib.rs","misc.rs","protocol_macro.rs","stable.rs","staging.rs","unstable.rs","wlr.rs"]};
sourcesIndex["wayland_scanner"] = {"name":"","files":["c_interfaces.rs","client_gen.rs","common.rs","interfaces.rs","lib.rs","parse.rs","protocol.rs","server_gen.rs","util.rs"]};
sourcesIndex["wayland_server"] = {"name":"","files":["client.rs","dispatch.rs","display.rs","global.rs","lib.rs","socket.rs"]};
sourcesIndex["wayland_sys"] = {"name":"","files":["client.rs","common.rs","cursor.rs","egl.rs","lib.rs","server.rs"]};
sourcesIndex["wayland_tests"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
